name: CI
on: [push]
jobs:
  # test:
  #   ...
  deploy:
    name: "Deploy to staging"
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    # needs: test
    steps:
      - name: Configure SSH
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts

      - name: Stop the server
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}

      # - name: Check out the source
      #   run: ssh staging 'cd my-application && git fetch && git reset --hard origin/master'

      # - name: Start the server
      #   if: ${{ always() }}
      #   run: ssh staging 'sudo systemctl start my-application'